[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.17.0.0/16
local_net=192.168.1.0/24
external_media_address=192.168.1.5
external_signaling_address=192.168.1.5

;========== USER 1001 ==========
[1001-auth]
type=auth
auth_type=userpass
password=pass1001
username=1001

[1001-aor]
type=aor
max_contacts=2
remove_existing=yes
qualify_frequency=30

[1001]
type=endpoint
context=default
transport=transport-udp
disallow=all
allow=ulaw
auth=1001-auth
aors=1001-aor
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

;========== USER 1002 ==========
[1002-auth]
type=auth
auth_type=userpass
password=pass1002
username=1002

[1002-aor]
type=aor
max_contacts=2
remove_existing=yes
qualify_frequency=30

[1002]
type=endpoint
context=default
transport=transport-udp
disallow=all
allow=ulaw
auth=1002-auth
aors=1002-aor
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes