[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060;he can accebet
local_net=172.17.0.0/16;Docker Network
local_net=192.168.1.0/24; Pc addres of Your Home/office wifi
external_media_address=192.168.1.5
external_signaling_address=192.168.1.5

;========== USER 1001 ==========
[auth1001]
type=auth
auth_type=userpass
password=pass1001
username=1001

[aor1001]
type=aor
max_contacts=2
remove_existing=yes
qualify_frequency=30

[1001]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth1001
aors=aor1001
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

# local_net: We define two of these 
# because Asterisk needs to know what is "internal.
# " One is for the Docker internal network (the 172.x.x.x range) 
# and one is for your Home/Office network (the 192.168.x.x range). 
# This helps Asterisk decide if it needs to do "NAT" 
# (Network Address Translation).
# external_media_address & external_signaling_address: 
# This is the most important part for Docker. 
# Asterisk is inside a "container" and thinks 
# its IP is something like 172.17.0.2. But your phone 
# (MicroSIP) is outside, on your PC. If Asterisk tells
#  the phone "Send audio to 172.17.0.2," the phone will 
#  fail because it can't see that private address.
#   We use these "External" settings to 
#   tell the phone: "Hey, I'm inside a container,
#    but please send my voice and signals to 
#    my PC's real IP address instead."

;========== USER 1002 ==========
[auth1002]
type=auth
auth_type=userpass
password=pass1002
username=1002

[aor1002]
type=aor
max_contacts=2
remove_existing=yes
qualify_frequency=30

[1002]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth1002
aors=aor1002
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes